### ISSUE TITLE
Error trying to build on ubuntu 16.04...

### ISSUE THREAD

**Issue by fstltna** [Thynix/Cavez-of-Phear#2]
I get several errors like this:
```
keys.o: In function `keys_menu':
keys.c:(.text+0xa19): undefined reference to `newwin'
keys.c:(.text+0xa2b): undefined reference to `wmove'
keys.c:(.text+0xa42): undefined reference to `waddnstr'
keys.c:(.text+0xa6c): undefined reference to `wrefresh'
keys.c:(.text+0xa73): undefined reference to `stdscr'
keys.c:(.text+0xa78): undefined reference to `wgetch'
keys.c:(.text+0xb80): undefined reference to `wmove'
keys.c:(.text+0xb9b): undefined reference to `waddnstr'

```
Any ideas?

**Comment by brefre** [comment]
You are probably missing a ncurses development pacakge, typically called something like ncurses-dev or ncurses-devel
